from __future__ import annotations

from qvglc.ir.model import Module
from qvglc.lvgl_probe.probe import LvglCapabilities
from qvglc.profile import Profile

_FONT_DEFINES = {
    "montserrat_14": "LV_FONT_MONTSERRAT_14",
    "montserrat_36": "LV_FONT_MONTSERRAT_36",
    "montserrat_48": "LV_FONT_MONTSERRAT_48",
}


def collect_required_fonts(mod: Module, profile: Profile) -> set[str]:
    fonts: set[str] = set()
    for node in mod.nodes:
        if node.kind == "Text":
            px = int(node.properties.get("font.pixelSize", 14))
            fonts.add(profile.font_for_pixel_size(px))
    if not fonts:
        fonts.add("montserrat_14")
    return fonts


def emit_qvgl_lv_conf(
    caps: LvglCapabilities,
    *,
    fonts: set[str],
    use_image: bool,
) -> str:
    font_lines = []
    for font_id in sorted(fonts):
        define = _FONT_DEFINES.get(font_id)
        if define:
            font_lines.append(
                f"#ifndef {define}\n#define {define} 1\n#endif"
            )
    image_block = ""
    if use_image:
        image_block = """
#ifndef LV_USE_IMAGE
#define LV_USE_IMAGE 1
#endif
"""
    return f"""/* Generated by qvglc — merge into project lv_conf / sdkconfig */
#ifndef QVGL_LV_CONF_H
#define QVGL_LV_CONF_H

/* LVGL {caps.version_string} @ {caps.lvgl_path} */

#ifndef LV_USE_ARC
#define LV_USE_ARC 1
#endif

#ifndef LV_USE_LABEL
#define LV_USE_LABEL 1
#endif

#ifndef LV_USE_SCALE
#define LV_USE_SCALE 1
#endif

#ifndef LV_USE_ANIM
#define LV_USE_ANIM 1
#endif
{image_block}
{chr(10).join(font_lines)}

#endif /* QVGL_LV_CONF_H */
"""


def emit_qvgl_lvgl_config(*, fonts: set[str], use_image: bool) -> str:
    kconfig = [
        "config LV_USE_ARC",
        "    bool",
        "    default y",
        "",
        "config LV_USE_LABEL",
        "    bool",
        "    default y",
        "",
        "config LV_USE_SCALE",
        "    bool",
        "    default y",
        "",
        "config LV_USE_ANIM",
        "    bool",
        "    default y",
        "",
    ]
    if use_image:
        kconfig += [
            "config LV_USE_IMAGE",
            "    bool",
            "    default y",
            "",
        ]
    for font_id in sorted(fonts):
        define = _FONT_DEFINES.get(font_id)
        if define:
            kconfig += [
                f"config {define}",
                "    bool",
                "    default y",
                "",
            ]
    return "# Generated by qvglc — rsource from Kconfig.projbuild\n" + "\n".join(kconfig)


def emit_qvgl_sources_cmake(lvgl_path: str, module: str, *, with_assets: bool = False) -> str:
    assets_line = ""
    if with_assets:
        assets_line = f'\n    "${{CMAKE_CURRENT_LIST_DIR}}/qvgl_{module}_assets.c"'
    return f"""# Generated by qvglc
set(QVGL_LVGL_PATH "{lvgl_path}" CACHE PATH "LVGL tree used by QVGL emit")
set(QVGL_GENERATED_UI
    "${{CMAKE_CURRENT_LIST_DIR}}/ui_{module}.c"{assets_line}
)
"""
