from __future__ import annotations

from pathlib import Path

from qvglc.ir.model import Module
from qvglc.lvgl_probe.probe import LvglCapabilities
from qvglc.profile import Profile

_FONT_DEFINES = {
    "montserrat_14": "LV_FONT_MONTSERRAT_14",
    "montserrat_36": "LV_FONT_MONTSERRAT_36",
    "montserrat_48": "LV_FONT_MONTSERRAT_48",
}

_LV_WIDGET_KCONFIG = (
    "LV_USE_ARC",
    "LV_USE_LABEL",
    "LV_USE_BUTTON",
    "LV_USE_SLIDER",
    "LV_USE_SWITCH",
    "LV_USE_CHECKBOX",
    "LV_USE_CHART",
    "LV_USE_SCALE",
    "LV_USE_ANIM",
)


def collect_required_fonts(mod: Module, profile: Profile) -> set[str]:
    fonts: set[str] = set()
    for node in mod.nodes:
        if node.kind in ("Text", "ToolButton"):
            px = int(node.properties.get("font.pixelSize", 14))
            fonts.add(profile.font_for_pixel_size(px))
    if not fonts:
        fonts.add("montserrat_14")
    return fonts


def emit_qvgl_lv_conf(
    caps: LvglCapabilities,
    *,
    fonts: set[str],
    use_image: bool,
) -> str:
    font_lines = []
    for font_id in sorted(fonts):
        define = _FONT_DEFINES.get(font_id)
        if define:
            font_lines.append(
                f"#ifndef {define}\n#define {define} 1\n#endif"
            )
    image_block = ""
    if use_image:
        image_block = """
#ifndef LV_USE_IMAGE
#define LV_USE_IMAGE 1
#endif
"""
    return f"""/* Generated by qvglc — merge into project lv_conf / sdkconfig */
#ifndef QVGL_LV_CONF_H
#define QVGL_LV_CONF_H

/* LVGL {caps.version_string} @ {caps.lvgl_path} */

#ifndef LV_USE_ARC
#define LV_USE_ARC 1
#endif

#ifndef LV_USE_LABEL
#define LV_USE_LABEL 1
#endif

#ifndef LV_USE_BUTTON
#define LV_USE_BUTTON 1
#endif

#ifndef LV_USE_SLIDER
#define LV_USE_SLIDER 1
#endif

#ifndef LV_USE_SWITCH
#define LV_USE_SWITCH 1
#endif

#ifndef LV_USE_CHECKBOX
#define LV_USE_CHECKBOX 1
#endif

#ifndef LV_USE_CHART
#define LV_USE_CHART 1
#endif

#ifndef LV_USE_SCALE
#define LV_USE_SCALE 1
#endif

#ifndef LV_USE_ANIM
#define LV_USE_ANIM 1
#endif
{image_block}
{chr(10).join(font_lines)}

#endif /* QVGL_LV_CONF_H */
"""


def _kconfig_widget_blocks() -> list[str]:
    blocks: list[str] = []
    for sym in _LV_WIDGET_KCONFIG:
        blocks += [f"config {sym}", "    bool", "    default y", ""]
    return blocks


def _sdkconfig_enable_lines(*, fonts: set[str], use_image: bool) -> list[str]:
    lines = [f"CONFIG_{sym}=y" for sym in _LV_WIDGET_KCONFIG]
    if use_image:
        lines.append("CONFIG_LV_USE_IMAGE=y")
    for font_id in sorted(fonts):
        define = _FONT_DEFINES.get(font_id)
        if define:
            lines.append(f"CONFIG_{define}=y")
    return lines


def emit_qvgl_lvgl_config(*, fonts: set[str], use_image: bool) -> str:
    kconfig = _kconfig_widget_blocks()
    if use_image:
        kconfig += [
            "config LV_USE_IMAGE",
            "    bool",
            "    default y",
            "",
        ]
    for font_id in sorted(fonts):
        define = _FONT_DEFINES.get(font_id)
        if define:
            kconfig += [
                f"config {define}",
                "    bool",
                "    default y",
                "",
            ]
    return "# Generated by qvglc — rsource from Kconfig.projbuild\n" + "\n".join(kconfig)


def emit_qvgl_sdkconfig_defaults(*, fonts: set[str], use_image: bool) -> str:
    lines = _sdkconfig_enable_lines(fonts=fonts, use_image=use_image)
    header = "# Generated by qvglc — wire via SDKCONFIG_DEFAULTS / compile_ui.sh\n"
    return header + "\n".join(lines) + "\n"


def merge_sdkconfig_fragment(fragment: Path, sdkconfig: Path) -> bool:
    """Enable CONFIG_*=y keys from fragment in an existing sdkconfig file."""
    wanted: dict[str, str] = {}
    for raw in fragment.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("CONFIG_") and line.endswith("=y"):
            wanted[line.split("=", 1)[0]] = line

    if not wanted:
        return False

    text = sdkconfig.read_text(encoding="utf-8")
    trailing_nl = text.endswith("\n")
    out: list[str] = []
    present: set[str] = set()
    changed = False

    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("# CONFIG_") and stripped.endswith(" is not set"):
            key = stripped[2:].split(" ", 1)[0]
            if key in wanted:
                out.append(wanted[key])
                present.add(key)
                changed = True
                continue
        if stripped.startswith("CONFIG_") and "=y" in stripped:
            key = stripped.split("=", 1)[0]
            present.add(key)
        out.append(raw)

    for key in sorted(wanted):
        if key not in present:
            out.append(wanted[key])
            changed = True

    if changed:
        merged = "\n".join(out)
        if trailing_nl:
            merged += "\n"
        sdkconfig.write_text(merged, encoding="utf-8")
    return changed


def emit_qvgl_sources_cmake(lvgl_path: str, module: str, *, with_assets: bool = False) -> str:
    assets_line = ""
    if with_assets:
        assets_line = f'\n    "${{CMAKE_CURRENT_LIST_DIR}}/qvgl_{module}_assets.c"'
    return f"""# Generated by qvglc
set(QVGL_LVGL_PATH "{lvgl_path}" CACHE PATH "LVGL tree used by QVGL emit")
set(QVGL_GENERATED_UI
    "${{CMAKE_CURRENT_LIST_DIR}}/ui_{module}.c"{assets_line}
)
"""
